version: "3.8"

services:
  backend:
    build: .
    container_name: quiz-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    command: ["sh", "-c", "npm run wait-for-db && npm start"]

  db:
    image: mysql:8
    container_name: quiz-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: quizapp
      MYSQL_USER: quizuser
      MYSQL_PASSWORD: quizpass
    ports:
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: quiz-redis
    restart: always
    ports:
      - "6380:6379" 

volumes:
  db_data:
